//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SodomaInn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int IdCliente { get; set; }
        public string NombreCliente { get; set; }
        public string Curp { get; set; }
        public string Telefono { get; set; }
        public bool Estatus { get; set; }
        public System.DateTime FechaAlta { get; set; }
    }
}
