//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SodomaInn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosReservacion
    {
        public int IdPago { get; set; }
        public string FormaPago { get; set; }
        public decimal MontoPago { get; set; }
        public decimal Comision { get; set; }
        public string Referencia { get; set; }
        public int IdReservacion { get; set; }
    
        public virtual Reservacion Reservacion { get; set; }
    }
}
